dialect = "us"
auto_sync = false
update_check = true
search_mode = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_key_binding = "host"
style = "compact"
inline_height = 20
show_preview = true
max_preview_height = 4
enter_accept = true
keymap_mode = "vim-insert"

secrets_filter = true
history_filter = [
    "^export ",
    "^set -x ",
    "token",
    "password",
    "secret",
]
