general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]
general.live_config_reload = true
[terminal]
osc52 = "CopyPaste"
shell = { program = "/opt/homebrew/bin/fish", args = ["--login"] }

[font.normal]
family = "FantasqueSansM Nerd Font"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font]
size = 14.0

[window]
padding = { x = 8, y = 8 }
decorations = "Buttonless"
opacity = 0.95
option_as_alt = "Both"
blur = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[scrolling]
history = 50000
multiplier = 5

[[keyboard.bindings]]
action = "ToggleViMode"
key = "S"
mods = "Control"

[colors]
transparent_background_colors = true

[env]
TERM = "xterm-256color"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[hints.enabled]]
command = "open"
binding = { key = "G", mods = "Control|Shift" }
regex = "[0-9a-f]{7,40}"

[[hints.enabled]]
command = "open"
binding = { key = "F", mods = "Control|Shift" }
regex = "~/[A-Za-z0-9._~/-]+|(/[A-Za-z0-9._~-]+)+"
